image: docker/dind


stages:
  - build

before_script:
  - export FRONTEND_IMAGE_PROD=$CI_REGISTRY_IMAGE:conver-pdf
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - export MINWAIT=0
  - export MAXWAIT=20


build-product:
  stage: build
  script:
    - docker build --build-arg NODE_ENV=production -t $FRONTEND_IMAGE_PROD .
    - docker push $FRONTEND_IMAGE_PROD

